version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/JeremyAnsel.Xwa.Opt" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore JeremyAnsel.Xwa.Opt\JeremyAnsel.Xwa.Opt.sln

build:
  project: JeremyAnsel.Xwa.Opt\JeremyAnsel.Xwa.Opt.sln
  publish_nuget: true
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: ez3RLsSaraf05zX77AqWyz+gYbT+5eM7jdIq7Fv43DXPp5+YscPbW5yb7owDfyHd
  skip_symbols: true
  on:
    branch: master
    DEPLOY: True
